ConfigLoader - add additional params
Mini-IT/SnipeUnityPackage pull request #13
Opened 2024-12-19 06:31 UTC by MaximFonariuc

Теперь параметры храняться в в отдельном поле и заполняется в методе `SetRequestParams()`, Вынес логику формирования запроса запроса на сервер в `SnipeConfigLoadingService.cs`, а также теперь список формируется с доп.параметрами. 
Добавлен метод `Reset()` для сброса текущих значений и повторной выгрузки конфига.

2024-12-19 08:22 UTC, gluks requested changes

2024-12-19 08:22 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoadingService.cs
> +			_config = null;
сначала нужно остановить загрузку (которая теоретически может выполняться в данный момент) через CancellationToken. иначе она завершится в параллельном потоке и присвоит своё значение конфигу вне зависимости от того, что тут ему присваивается null

2024-12-19 08:31 UTC, gluks requested changes
почему-то в прошлый раз этот комментарий потерялся

2024-12-19 08:31 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoader.cs
> +		public void SetRequestParams(string requestParams)
а тут целый ряд проблем
- это публичный метод, значит вызвать его может кто угодно с какими угодно параметрами, следовательно, требуется проверка валидности входящих значений
- насколько я вижу, этот метод вызывается всего один раз и при этом непосредственно перед вызовом Load. в этом случае в данном методе нет никакой необходимости - можно просто передавать аргументы в сам метод Load
- параметры запроса содежат необходимые значения и дополнительные. нельзя, чтобы какой-то внешний класс мог затереть обязательные параметры. Т.е. метод BuildRequestParamsJson более уместен в этом классе, а не во внешнем сервисе
итого можно сделать что-то типа такого:
```csharp
Load(Dictionary<string, object> additionalParams)
{
  string requestParamsJson = BuildRequestParamsJson(additionalParams);
  //...
```

2024-12-19 08:51 UTC, MaximFonariuc commented on Runtime/Snipe.Unity/Config/SnipeConfigLoader.cs
> +		public void SetRequestParams(string requestParams)
> а тут целый ряд проблем
> 
> * это публичный метод, значит вызвать его может кто угодно с какими угодно параметрами, следовательно, требуется проверка валидности входящих значений
> * насколько я вижу, этот метод вызывается всего один раз и при этом непосредственно перед вызовом Load. в этом случае в данном методе нет никакой необходимости - можно просто передавать аргументы в сам метод Load
> * параметры запроса содежат необходимые значения и дополнительные. нельзя, чтобы какой-то внешний класс мог затереть обязательные параметры. Т.е. метод BuildRequestParamsJson более уместен в этом классе, а не во внешнем сервисе
>   итого можно сделать что-то типа такого:
> 
> ```cs
> Load(Dictionary<string, object> additionalParams)
> {
>   string requestParamsJson = BuildRequestParamsJson(additionalParams);
>   //...
> ```

Согласен, перенесу `BuildRequestParamsJson()` в `SnipeConfigLoader()`, а additionalParams буду передавать в метод `Load()`

2024-12-20 11:59 UTC, gluks requested changes

2024-12-20 11:59 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoadingService.cs
> +		private CancellationTokenSource _loadingCancellation;
не всё так просто...
если класс содерит disposable поля, то и сам класс должен быть IDisposable со всеми вытекающими

2024-12-20 11:59 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoadingService.cs
> +			_loadingCancellation ??= new CancellationTokenSource();
во-первых, нельзя игнорировать уже имеющийся токен
```cs
_loadingCancellation = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
```
во-вторых, у тебя тут есть проверка на случай, если _loadingCancellation != null это хорошо, но нет никакого действия. Если у нас уже есть какой-то ранее созданный CTS, значит мы уже запустили загрузку и она сейчас уже в процессе - требуется принять решение, как с ней поступить: либо отменить старую, либо отменить новую и ждать окончания старой

2024-12-20 11:59 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoadingService.cs
> +				await UniTask.WaitUntil(() => SnipeServices.IsInitialized, PlayerLoopTiming.Update, _loadingCancellation.Token)
так можно, но только если используется LinkedTokenSource (см. выше), иначе мы игнорируем внешний cancellationToken, а он по логике главней нашего внутреннего

2024-12-20 11:59 UTC, gluks commented on Runtime/Snipe.Unity/Config/SnipeConfigLoadingService.cs
> +				if (_loadingCancellation.Token.IsCancellationRequested)
сохрани токен в локальную переменную вместо того, чтобы каждый раз вызывать свойство _loadingCancellation.Token
обращения к свойствам - это фактически вызов метода, а это значит, что под капотом выполняется целая куча промежуточных действий с сохранением стека и сменой контекста - можно оптимизировать одной строкой

2025-07-01 14:49 UTC, merged